### PR TITLE
Completion of initial next steps (omnisharp/omnisharp-scaffolding#1)

### PR DESCRIPTION
**Pull request by dmccaffery**
Removed all projects except CodeGeneration, which was renamed to
OmniSharp.Scaffolding
Dependencies are now pulled in through NuGet
Ensured KoreBuild continues to work
Building against latest available DNX sources and dependencies
Changed the license from Apache 2.0 to MIT (per OmniSharp standard)
Added a new, empty test project for unit tests
Updated the readme.md to elaborate on what OmniSharp.Scaffolding now is
and what its future goals are.

### CODE REVIEW

**Comment by itomek** [comment]
It look like you are using JetBrains [NotNull] annotations. Will we be using Resharper for this?

**Comment by Muchiachio** [comment]
It was forked before aspnet team did a [[NotNull] removal](https://github.com/aspnet/Scaffolding/commit/3c61398c5c4b091bca40eb076ce184e6155e9119), I guess it's just a legacy now.

**Comment by sayedihashimi** [comment]
FYI I won't be able to review for about a week as I'm on vacation.

If you get a :+1: from @Muchiachio then go ahead and merge.

**Comment by Muchiachio** [comment]
@dmccaffery I guess we should remove [NotNull] attributes as it relies on a paid product.
Other than that :shipit:

**Comment by itomek** [comment]
Well we could get Resharper OpenSource licenses of course but that would take time.

**Comment by dmccaffery** [comment]
My apologies to those who got assigned to this by accident; there is a bug in github on mobile devices where touches do not register correctly when attempting to make an assignment... :(

**Comment by david-driscoll** [comment]
That's a ton of stuff, but looks good :shipit:

**Pull request merged**
